export interface IOwnerInfo{
    CreatedBy?:string,
    CreatedDate?: Date,
    Database?: string,
    Description?: string,
    Email?: string,
    EnglishName?: string,
    FaceboolURL?: string,
    Id?: number,
    InURL?: string,
    InstagramURL?: string,
    Name?: string,
    PathImage?: string,
    Phone?: string,
    Phone1?: string,
    RecordCount?: number,
    TelegramURL?: string,
    UpdatedBy?: string,
    UpdatedDate?: Date,
    WorkingInfo?: string,
    YoutubeURL?: string,
}